export default {
  LoginBGImg: require('../assets/images/LoginBGImg.png'),
  Google: require('../assets/images/Google.png'),
  Apple: require('../assets/images/Apple.png'),
  FB: require('../assets/images/FB.png'),
  CoolBackground: require('../assets/images/CoolBackground.png'),
  DraftbitIcon: require('../assets/images/DraftbitIcon.png'),
  AppIcon: require('../assets/images/AppIcon.png'),
  Ramen: require('../assets/images/Ramen.jpg'),
  Fbicon: require('../assets/images/Fbicon.png'),
  Insta: require('../assets/images/Insta.png'),
  Twitter: require('../assets/images/Twitter.png'),
  Pin: require('../assets/images/Pin.png'),
  CourseSplash: require('../assets/images/CourseSplash.png'),
  NoContentIllustration: require('../assets/images/NoContentIllustration.png'),
  CharlieGreen3JmfENcL24MUnsplash: require('../assets/images/CharlieGreen3JmfENcL24MUnsplash.jpg'),
};
